spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_URL}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    mongodb:
      uri: mongodb+srv://jkw:5033@kore.iv5scds.mongodb.net/chatdb?retryWrites=true&w=majority&appName=kore

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

jwt:
  issuer: 32204027@dankook.ac.kr
  secret_key: ${JWT_SECRET_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: desc
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  show-actuator: true
  default-consumes-media-type: application/json
