server:
  port: 8080
  ssl:
    key-store: classpath:${KEY_STORE}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${KEY_ALIAS}
    trust-store: classpath:${MINIO_TRUST_STORE}
    trust-store-password: ${MINIO_TRUST_STORE_PASSWORD}
    trust-store-type: JKS

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_URL}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    mongodb:
      uri: mongodb+srv://jkw:5033@kore.iv5scds.mongodb.net/chatdb?retryWrites=true&w=majority&appName=kore

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: desc
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  show-actuator: true
  default-consumes-media-type: application/json

minio:
  endpoint: https://object-api.tetraplace.com
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucketName: kore
